import 'dart:convert';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;
import '../models/food_item.dart';
import '../models/restaurant_model.dart';

class FoodService {
  // Country & Global Cuisines
  static final List<Map<String, String>> countryCuisines = [
    {'name': 'All', 'country': 'All', 'flag': '🌐'},
    {'name': 'Sri Lankan', 'country': 'Sri Lanka', 'flag': '🇱🇰'},
    {'name': 'Indian', 'country': 'India', 'flag': '🇮🇳'},
    {'name': 'Chinese', 'country': 'China', 'flag': '🇨🇳'},
    {'name': 'Italian', 'country': 'Italy', 'flag': '🇮🇹'},
    {'name': 'American', 'country': 'USA', 'flag': '🇺🇸'},
    {'name': 'Arabian', 'country': 'Arabia', 'flag': '🇦🇪'},
    {'name': 'Japanese', 'country': 'Japan', 'flag': '🇯🇵'},
    {'name': 'Thai', 'country': 'Thailand', 'flag': '🇹🇭'},
  ];

  // Food Categories
  static final List<Map<String, dynamic>> categories = [
    {'name': 'All', 'icon': '✨', 'badge': ''},
    {'name': 'Rice & Curry', 'icon': '🍚', 'badge': 'Top Pick'},
    {'name': 'Kottu Mania', 'icon': '🍳', 'badge': 'Hot 🔥'},
    {'name': 'Biryani Feast', 'icon': '🍲', 'badge': 'Popular'},
    {'name': 'Burgers & Grill', 'icon': '🍔', 'badge': ''},
    {'name': 'Pizza & Pasta', 'icon': '🍕', 'badge': ''},
    {'name': 'Noodles & Wok', 'icon': '🍜', 'badge': ''},
    {'name': 'Short Eats', 'icon': '🥟', 'badge': ''},
    {'name': 'Desserts & Sweets', 'icon': '🍰', 'badge': ''},
    {'name': 'Cafe & Drinks', 'icon': '☕', 'badge': ''},
  ];

  static final List<SpiceOption> bonchiSpiceOptions = [
    SpiceOption(id: 'sp1', name: 'Mild', iconEmoji: '🍃', extraPriceLkr: 0),
    SpiceOption(id: 'sp2', name: 'Medium Spicy', iconEmoji: '🌶️', extraPriceLkr: 0),
    SpiceOption(id: 'sp3', name: 'Nai Miris Hot', iconEmoji: '🔥', extraPriceLkr: 500),
  ];

  // Curated Partner Restaurants
  static final List<RestaurantModel> mockRestaurants = [
    const RestaurantModel(
      id: 'rest_pilawaos',
      name: 'Pilawaos Grand Hotel',
      sinhalaName: 'පිලාවුස් ග්‍රෑන්ඩ් හොටෙල්',
      cuisine: 'Sri Lankan • Kottu & Roti • Halal',
      country: 'Sri Lanka',
      flagEmoji: '🇱🇰',
      rating: 4.9,
      reviewCountText: '3.2k+',
      deliveryTime: '20-25 min',
      deliveryFeeLkr: 150.0,
      address: 'No. 142, Galle Road, Colombo 03',
      coverImageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
      logoUrl: 'assets/images/bonchi_logo.png',
      badgeTag: 'NIGHT HIT',
      menuCategories: ['All', 'Kottu Specials', 'Roti & Breads', 'Curries', 'Beverages'],
    ),
    const RestaurantModel(
      id: 'rest_upalis',
      name: "Upali's by Nawaloka",
      sinhalaName: 'උපාලිස් බයි නවලෝක',
      cuisine: 'Authentic Village Rice & Curry • Seafood',
      country: 'Sri Lanka',
      flagEmoji: '🇱🇰',
      rating: 4.8,
      reviewCountText: '2.1k+',
      deliveryTime: '30-35 min',
      deliveryFeeLkr: 180.0,
      address: 'No. 65, C.W.W. Kannangara Mawatha, Colombo 07',
      coverImageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
      logoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=200&q=80',
      badgeTag: 'VILLAGE FEAST',
      menuCategories: ['All', 'Claypot Rice', 'Curries & Sambols', 'Traditional Sweets'],
    ),
    const RestaurantModel(
      id: 'rest_bombay',
      name: 'Bombay Sweet Mahal & Biryani',
      sinhalaName: 'බොම්බේ බිරියානි හවුස්',
      cuisine: 'North & South Indian • Dum Biryani • Halal',
      country: 'India',
      flagEmoji: '🇮🇳',
      rating: 4.8,
      reviewCountText: '2.9k+',
      deliveryTime: '25-30 min',
      deliveryFeeLkr: 160.0,
      address: 'No. 88, Galle Road, Colombo 04',
      coverImageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80',
      logoUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=200&q=80',
      badgeTag: 'SPICE KING',
      menuCategories: ['All', 'Biryani Specials', 'Tandoori & Curries', 'Indian Sweets'],
    ),
    const RestaurantModel(
      id: 'rest_dragon',
      name: 'Golden Dragon Palace',
      sinhalaName: 'ගෝල්ඩන් ඩ්‍රැගන් චයිනීස්',
      cuisine: 'Authentic Cantonese & Szechuan • Wok Seafood',
      country: 'China',
      flagEmoji: '🇨🇳',
      rating: 4.7,
      reviewCountText: '1.9k+',
      deliveryTime: '25-35 min',
      deliveryFeeLkr: 190.0,
      address: 'No. 21, Alfred Place, Colombo 03',
      coverImageUrl: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=800&q=80',
      logoUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=200&q=80',
      badgeTag: 'HOT BUTTER',
      menuCategories: ['All', 'Fried Rice', 'Wok Seafood', 'Dim Sum & Soups'],
    ),
    const RestaurantModel(
      id: 'rest_giovanni',
      name: "Giovanni's Wood-Fired Pizza",
      sinhalaName: 'ජියෝවානිස් පීසා',
      cuisine: 'Napoli Pizza • Handcrafted Pasta • Italian',
      country: 'Italy',
      flagEmoji: '🇮🇹',
      rating: 4.9,
      reviewCountText: '3.5k+',
      deliveryTime: '25-30 min',
      deliveryFeeLkr: 170.0,
      address: 'No. 145, Thimbirigasyaya Road, Colombo 05',
      coverImageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
      logoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=200&q=80',
      badgeTag: 'WOOD FIRED',
      menuCategories: ['All', 'Artisan Pizzas', 'Handmade Pastas', 'Desserts'],
    ),
    const RestaurantModel(
      id: 'rest_manhattan',
      name: 'Manhattan Smash Burgers & Grill',
      sinhalaName: 'මෑන්හැටන් බර්ගර්ස්',
      cuisine: 'American Smash Burgers • Wings • Loaded Fries',
      country: 'USA',
      flagEmoji: '🇺🇸',
      rating: 4.8,
      reviewCountText: '2.4k+',
      deliveryTime: '20-25 min',
      deliveryFeeLkr: 150.0,
      address: 'No. 32, Ward Place, Colombo 07',
      coverImageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
      logoUrl: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=200&q=80',
      badgeTag: 'TRUFFLE SMASH',
      menuCategories: ['All', 'Smash Burgers', 'Crispy Wings', 'Sides & Shakes'],
    ),
    const RestaurantModel(
      id: 'rest_arabian',
      name: 'Arabian Knights Express',
      sinhalaName: 'ඇරබියන් නයිට්ස්',
      cuisine: 'Shawarma • Chicken Mandi • Kebabs • Halal',
      country: 'Arabia',
      flagEmoji: '🇦🇪',
      rating: 4.7,
      reviewCountText: '2.7k+',
      deliveryTime: '20-30 min',
      deliveryFeeLkr: 140.0,
      address: 'No. 379, Galle Road, Colombo 03',
      coverImageUrl: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=800&q=80',
      logoUrl: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=200&q=80',
      badgeTag: 'MANDI POT',
      menuCategories: ['All', 'Shawarma Rolls', 'Mandi & Rice', 'Charcoal Grills'],
    ),
    const RestaurantModel(
      id: 'rest_samurai',
      name: 'Samurai Sushi & Ramen Bar',
      sinhalaName: 'සමුරායි සුෂි සහ රාමන්',
      cuisine: 'Japanese Bento • Ramen Bowls • Teriyaki',
      country: 'Japan',
      flagEmoji: '🇯🇵',
      rating: 4.9,
      reviewCountText: '1.5k+',
      deliveryTime: '30-40 min',
      deliveryFeeLkr: 200.0,
      address: 'No. 12, Rosmead Place, Colombo 07',
      coverImageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
      logoUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=200&q=80',
      badgeTag: 'FRESH SUSHI',
      menuCategories: ['All', 'Sushi Platters', 'Ramen Bowls', 'Bento Boxes'],
    ),
  ];

  // Comprehensive Catalog of Food Items
  static final List<FoodItem> mockFoodItems = [
    // --- SRI LANKA 🇱🇰 ---
    FoodItem(
      id: 'b1',
      name: 'Chicken Cheese Kottu',
      sinhalaName: 'චිකන් චීස් කොත්තු',
      restaurantId: 'rest_pilawaos',
      restaurantName: 'Pilawaos Grand Hotel',
      restaurantSubtitle: 'Sri Lankan • Kottu & Roti • Halal • Late Night',
      country: 'Sri Lanka',
      category: 'Kottu Mania',
      menuCategory: 'Kottu Specials',
      description: 'Chopped godamba roti tossed on hot griddle with spiced tender roast chicken, farm-fresh eggs, leeks, carrots, rich curry gravy, and crowned with bubbling melted mozzarella cheese.',
      priceLkr: 2100.0,
      rating: 4.9,
      reviewCountText: '3.2k+',
      deliveryTime: '20-25 min',
      deliveryFeeLkr: 150.0,
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: true,
      isSpecial: true,
      isHalal: true,
      servesText: 'Serves 1–2 • 650g',
      signatureTag: 'SIGNATURE HIT',
      signatureItemName: 'Chicken Cheese Kottu',
      signatureItemPriceLkr: 2100.0,
      spiceLevels: bonchiSpiceOptions,
    ),
    FoodItem(
      id: 'b2',
      name: 'Claypot Red Rice Feast',
      sinhalaName: 'මැටි වළං රතු බත් සමග මාලු',
      restaurantId: 'rest_upalis',
      restaurantName: "Upali's by Nawaloka",
      restaurantSubtitle: 'Traditional Rice & Curry • Village Style • Seafood',
      country: 'Sri Lanka',
      category: 'Rice & Curry',
      menuCategory: 'Claypot Rice',
      description: 'Steaming organic red kakulu rice served in authentic claypot with Jaffna crab curry, pol sambol, fried dried fish, brinjal moju, and gotukola sambol.',
      priceLkr: 2450.0,
      rating: 4.8,
      reviewCountText: '2.1k+',
      deliveryTime: '30-35 min',
      deliveryFeeLkr: 180.0,
      imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: true,
      isSpecial: false,
      isHalal: true,
      servesText: 'Serves 2 • 800g',
      signatureTag: 'VILLAGE SPECIAL',
      signatureItemName: 'Claypot Red Rice Feast',
      signatureItemPriceLkr: 2450.0,
      spiceLevels: bonchiSpiceOptions,
    ),
    FoodItem(
      id: 'b3',
      name: 'Spicy Mutton Roll (Box of 4)',
      sinhalaName: 'සැර එළුමස් රෝල්ස්',
      restaurantId: 'rest_pilawaos',
      restaurantName: 'Pilawaos Grand Hotel',
      restaurantSubtitle: 'Short Eats • Bakery • Patties & Rolls • Snacks',
      country: 'Sri Lanka',
      category: 'Short Eats',
      menuCategory: 'Roti & Breads',
      description: 'Golden crispy crumbed rolls filled with slow-cooked shredded devilled mutton, potatoes, and Sri Lankan black pepper spices.',
      priceLkr: 1200.0,
      rating: 4.7,
      reviewCountText: '1.8k+',
      deliveryTime: '15-20 min',
      deliveryFeeLkr: 120.0,
      imageUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: false,
      isSpecial: false,
      isHalal: true,
      servesText: 'Box of 4 Rolls',
      signatureTag: 'TEA TIME CRAVING',
      signatureItemName: 'Spicy Mutton Roll (Box of 4)',
      signatureItemPriceLkr: 1200.0,
      spiceLevels: bonchiSpiceOptions,
    ),
    FoodItem(
      id: 'sl_crab',
      name: 'Jaffna Lagoon Mud Crab Curry',
      sinhalaName: 'යාපනයේ මඩ කකුළු කරිය',
      restaurantId: 'rest_upalis',
      restaurantName: "Upali's by Nawaloka",
      restaurantSubtitle: 'Authentic Seafood • Village Flavours',
      country: 'Sri Lanka',
      category: 'Rice & Curry',
      menuCategory: 'Curries & Sambols',
      description: 'Succulent lagoon mud crab simmered in fiery Jaffna roasted curry powder, thick coconut milk, and fragrant murunga leaves.',
      priceLkr: 3800.0,
      rating: 4.9,
      reviewCountText: '1.4k+',
      deliveryTime: '35-40 min',
      deliveryFeeLkr: 180.0,
      imageUrl: 'https://images.unsplash.com/photo-1559847844-5315695dadae?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: true,
      isSpecial: true,
      isHalal: true,
      servesText: 'Serves 2 • Whole Crab',
      signatureTag: 'CHEF PRIDE',
      signatureItemName: 'Jaffna Lagoon Mud Crab Curry',
      signatureItemPriceLkr: 3800.0,
      spiceLevels: bonchiSpiceOptions,
    ),

    // --- INDIA 🇮🇳 ---
    FoodItem(
      id: 'in_biryani',
      name: 'Hyderabadi Chicken Dum Biryani',
      sinhalaName: 'හයිද්‍රාබාද් චිකන් දම් බිරියානි',
      restaurantId: 'rest_bombay',
      restaurantName: 'Bombay Sweet Mahal & Biryani',
      restaurantSubtitle: 'North & South Indian • Dum Biryani • Halal',
      country: 'India',
      category: 'Biryani Feast',
      menuCategory: 'Biryani Specials',
      description: 'Aromatic long-grain basmati rice cooked on slow dum with saffron, marinated chicken thighs, mint, fried onions, served with cooling raita & salan gravy.',
      priceLkr: 2250.0,
      rating: 4.9,
      reviewCountText: '4.1k+',
      deliveryTime: '25-30 min',
      deliveryFeeLkr: 160.0,
      imageUrl: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: true,
      isSpecial: true,
      isHalal: true,
      servesText: 'Serves 1–2 • 700g',
      signatureTag: 'ROYAL DUM',
      signatureItemName: 'Hyderabadi Chicken Dum Biryani',
      signatureItemPriceLkr: 2250.0,
      spiceLevels: bonchiSpiceOptions,
    ),
    FoodItem(
      id: 'in_butter_chicken',
      name: 'Butter Chicken & Garlic Naan',
      sinhalaName: 'බටර් චිකන් සහ ගාර්ලික් නාන්',
      restaurantId: 'rest_bombay',
      restaurantName: 'Bombay Sweet Mahal & Biryani',
      restaurantSubtitle: 'North Indian Classics • Tandoor Breads',
      country: 'India',
      category: 'Biryani Feast',
      menuCategory: 'Tandoori & Curries',
      description: 'Tandoor-charred chicken tikka simmered in a velvet tomato, butter, and cashew cream sauce, served with two crispy garlic butter naans.',
      priceLkr: 2350.0,
      rating: 4.8,
      reviewCountText: '3.0k+',
      deliveryTime: '25-30 min',
      deliveryFeeLkr: 160.0,
      imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: true,
      isSpecial: false,
      isHalal: true,
      servesText: 'Curry + 2 Naans',
      signatureTag: 'TANDOOR STAR',
      signatureItemName: 'Butter Chicken & Garlic Naan',
      signatureItemPriceLkr: 2350.0,
      spiceLevels: bonchiSpiceOptions,
    ),
    FoodItem(
      id: 'in_gulab',
      name: 'Warm Gulab Jamun with Kulfi (4 Pcs)',
      sinhalaName: 'ගුලාබ් ජාමුන් සහ කුල්ෆි',
      restaurantId: 'rest_bombay',
      restaurantName: 'Bombay Sweet Mahal & Biryani',
      restaurantSubtitle: 'Traditional Indian Sweets',
      country: 'India',
      category: 'Desserts & Sweets',
      menuCategory: 'Indian Sweets',
      description: 'Melt-in-mouth milk-solid dumplings soaked in rose and cardamom sugar syrup, served with creamy pistachio kulfi ice cream.',
      priceLkr: 890.0,
      rating: 4.9,
      reviewCountText: '950+',
      deliveryTime: '15-20 min',
      deliveryFeeLkr: 100.0,
      imageUrl: 'https://images.unsplash.com/photo-1541832676-9b763b0239ab?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: false,
      isSpecial: false,
      isHalal: true,
      servesText: '4 Pieces',
      signatureTag: 'SWEET TREAT',
      signatureItemName: 'Warm Gulab Jamun',
      signatureItemPriceLkr: 890.0,
    ),

    // --- CHINA 🇨🇳 ---
    FoodItem(
      id: 'cn_hbc',
      name: 'Colombo Hot Butter Cuttlefish',
      sinhalaName: 'හොට් බටර් දැල්ලෝ',
      restaurantId: 'rest_dragon',
      restaurantName: 'Golden Dragon Palace',
      restaurantSubtitle: 'Sri Lankan Chinese • Signature Seafood',
      country: 'China',
      category: 'Noodles & Wok',
      menuCategory: 'Wok Seafood',
      description: 'Crispy batter-fried cuttlefish rings tossed with butter, spring onions, capsicum, dry red chilies, and sweet wok spices.',
      priceLkr: 2650.0,
      rating: 4.9,
      reviewCountText: '3.8k+',
      deliveryTime: '25-30 min',
      deliveryFeeLkr: 190.0,
      imageUrl: 'https://images.unsplash.com/photo-1534422298391-e4f8c172dddb?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: true,
      isSpecial: true,
      isHalal: true,
      servesText: 'Serves 2 • 450g',
      signatureTag: 'ISLAND LEGEND',
      signatureItemName: 'Hot Butter Cuttlefish',
      signatureItemPriceLkr: 2650.0,
      spiceLevels: bonchiSpiceOptions,
    ),
    FoodItem(
      id: 'cn_fried_rice',
      name: 'Yang Chow Chicken & Prawn Fried Rice',
      sinhalaName: 'යැං චවු ෆ්‍රයිඩ් රයිස්',
      restaurantId: 'rest_dragon',
      restaurantName: 'Golden Dragon Palace',
      restaurantSubtitle: 'Wok Master Rice & Noodles',
      country: 'China',
      category: 'Rice & Curry',
      menuCategory: 'Fried Rice',
      description: 'Wok-charred fragrant basmati rice tossed with roasted chicken cubes, tiger prawns, egg ribbons, sweet peas, and light sesame soy.',
      priceLkr: 1950.0,
      rating: 4.7,
      reviewCountText: '2.5k+',
      deliveryTime: '20-25 min',
      deliveryFeeLkr: 160.0,
      imageUrl: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: true,
      isSpecial: false,
      isHalal: true,
      servesText: 'Serves 2 • 650g',
      signatureTag: 'WOK BREATH',
      signatureItemName: 'Yang Chow Fried Rice',
      signatureItemPriceLkr: 1950.0,
      spiceLevels: bonchiSpiceOptions,
    ),

    // --- ITALY 🇮🇹 ---
    FoodItem(
      id: 'it_pizza',
      name: 'Margherita & Pepperoni Wood-Fired Pizza',
      sinhalaName: 'වුඩ් ෆයර්ඩ් මාගරිටා පීසා',
      restaurantId: 'rest_giovanni',
      restaurantName: "Giovanni's Wood-Fired Pizza",
      restaurantSubtitle: 'Napoli Pizza • Handcrafted Pasta • Italian',
      country: 'Italy',
      category: 'Pizza & Pasta',
      menuCategory: 'Artisan Pizzas',
      description: 'Slow-fermented sourdough base blistered in a 450°C wood oven, topped with San Marzano tomato sauce, fresh mozzarella, spicy pepperoni, and aromatic basil.',
      priceLkr: 2950.0,
      rating: 4.9,
      reviewCountText: '3.6k+',
      deliveryTime: '25-30 min',
      deliveryFeeLkr: 170.0,
      imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: true,
      isSpecial: true,
      isHalal: true,
      servesText: '12 Inch Large (8 Slices)',
      signatureTag: 'AUTHENTIC NAPOLI',
      signatureItemName: 'Margherita & Pepperoni Pizza',
      signatureItemPriceLkr: 2950.0,
    ),
    FoodItem(
      id: 'it_pasta',
      name: 'Creamy Chicken Fettuccine Alfredo',
      sinhalaName: 'ක්‍රීමි චිකන් ඇල්ෆ්‍රෙඩෝ පැස්ටා',
      restaurantId: 'rest_giovanni',
      restaurantName: "Giovanni's Wood-Fired Pizza",
      restaurantSubtitle: 'Italian Pasta Classics',
      country: 'Italy',
      category: 'Pizza & Pasta',
      menuCategory: 'Handmade Pastas',
      description: 'Handcrafted fettuccine ribbon pasta tossed in rich parmesan cream, garlic butter, pan-seared chicken breast, and freshly cracked black pepper.',
      priceLkr: 2450.0,
      rating: 4.8,
      reviewCountText: '1.9k+',
      deliveryTime: '20-30 min',
      deliveryFeeLkr: 170.0,
      imageUrl: 'https://images.unsplash.com/photo-1645112411341-6c4fd023714a?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: true,
      isSpecial: false,
      isHalal: true,
      servesText: 'Serves 1 • 500g',
      signatureTag: 'PARMESAN CREAM',
      signatureItemName: 'Fettuccine Alfredo',
      signatureItemPriceLkr: 2450.0,
    ),

    // --- USA 🇺🇸 ---
    FoodItem(
      id: 'us_burger',
      name: 'Double Truffle Smash Burger',
      sinhalaName: 'ඩබල් ට්‍රෆල් ස්මෑෂ් බර්ගර්',
      restaurantId: 'rest_manhattan',
      restaurantName: 'Manhattan Smash Burgers & Grill',
      restaurantSubtitle: 'American Smash Burgers • Wings • Loaded Fries',
      country: 'USA',
      category: 'Burgers & Grill',
      menuCategory: 'Smash Burgers',
      description: 'Two smashed prime beef patties with crispy lacy edges, melted American cheddar, caramelized onions, pickles, and black truffle mayo in a toasted brioche bun.',
      priceLkr: 2600.0,
      rating: 4.9,
      reviewCountText: '3.1k+',
      deliveryTime: '20-25 min',
      deliveryFeeLkr: 150.0,
      imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: true,
      isSpecial: true,
      isHalal: true,
      servesText: 'Single Jumbo Burger',
      signatureTag: 'SMASH HERO',
      signatureItemName: 'Double Truffle Smash Burger',
      signatureItemPriceLkr: 2600.0,
    ),
    FoodItem(
      id: 'us_wings',
      name: 'Crispy Buffalo Wings with Blue Cheese',
      sinhalaName: 'ක්‍රිස්පි බෆලෝ විංග්ස්',
      restaurantId: 'rest_manhattan',
      restaurantName: 'Manhattan Smash Burgers & Grill',
      restaurantSubtitle: 'Game Day Specials',
      country: 'USA',
      category: 'Burgers & Grill',
      menuCategory: 'Crispy Wings',
      description: '8 jumbo crispy chicken wings tossed in tangy cayenne pepper buffalo sauce, served with cool ranch dip and celery sticks.',
      priceLkr: 1850.0,
      rating: 4.7,
      reviewCountText: '1.6k+',
      deliveryTime: '20-25 min',
      deliveryFeeLkr: 150.0,
      imageUrl: 'https://images.unsplash.com/photo-1527477321005-4d01d75b235c?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: false,
      isSpecial: false,
      isHalal: true,
      servesText: '8 Pieces Basket',
      signatureTag: 'CRISPY CRUNCH',
      signatureItemName: 'Buffalo Wings',
      signatureItemPriceLkr: 1850.0,
    ),

    // --- ARABIA 🇦🇪 ---
    FoodItem(
      id: 'ar_shawarma',
      name: 'Beirut Chicken Shawarma Jumbo Roll',
      sinhalaName: 'බීරූට් චිකන් ෂවර්මා',
      restaurantId: 'rest_arabian',
      restaurantName: 'Arabian Knights Express',
      restaurantSubtitle: 'Shawarma • Chicken Mandi • Kebabs • Halal',
      country: 'Arabia',
      category: 'Short Eats',
      menuCategory: 'Shawarma Rolls',
      description: 'Spit-roasted spiced chicken, garlic toum sauce, pickled cucumbers, and salted fries wrapped in warm Arabic saj flatbread and griddled crisp.',
      priceLkr: 1450.0,
      rating: 4.8,
      reviewCountText: '2.8k+',
      deliveryTime: '20-25 min',
      deliveryFeeLkr: 140.0,
      imageUrl: 'https://images.unsplash.com/photo-1561651823-34feb02250e4?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: true,
      isSpecial: true,
      isHalal: true,
      servesText: 'Jumbo 10 Inch Wrap',
      signatureTag: 'MIDDLE EAST NO.1',
      signatureItemName: 'Beirut Shawarma Roll',
      signatureItemPriceLkr: 1450.0,
      spiceLevels: bonchiSpiceOptions,
    ),
    FoodItem(
      id: 'ar_mandi',
      name: 'Royal Chicken Mandi Rice Platter',
      sinhalaName: 'රෝයල් චිකන් මැන්ඩි ප්ලැටර්',
      restaurantId: 'rest_arabian',
      restaurantName: 'Arabian Knights Express',
      restaurantSubtitle: 'Authentic Yemeni Mandi',
      country: 'Arabia',
      category: 'Biryani Feast',
      menuCategory: 'Mandi & Rice',
      description: 'Slow-smoked half chicken served over hawaij-spiced long basmati rice with dakous tomato salsa, garlic sauce, and roasted almonds.',
      priceLkr: 2550.0,
      rating: 4.8,
      reviewCountText: '2.2k+',
      deliveryTime: '25-35 min',
      deliveryFeeLkr: 140.0,
      imageUrl: 'https://images.unsplash.com/photo-1633964913295-ceb43826e7c9?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: true,
      isSpecial: false,
      isHalal: true,
      servesText: 'Serves 2 • Half Chicken',
      signatureTag: 'SMOKED MANDI',
      signatureItemName: 'Royal Chicken Mandi',
      signatureItemPriceLkr: 2550.0,
    ),

    // --- JAPAN 🇯🇵 ---
    FoodItem(
      id: 'jp_sushi',
      name: 'Tokyo Salmon & Tuna Sushi Platter',
      sinhalaName: 'සැමන් සහ ටූනා සුෂි ප්ලැටර්',
      restaurantId: 'rest_samurai',
      restaurantName: 'Samurai Sushi & Ramen Bar',
      restaurantSubtitle: 'Japanese Bento • Ramen Bowls • Teriyaki',
      country: 'Japan',
      category: 'Short Eats',
      menuCategory: 'Sushi Platters',
      description: '12 pcs artisan sushi platter featuring fresh Atlantic salmon nigiri, spicy tuna maki, avocado California rolls, pickled ginger, and wasabi.',
      priceLkr: 3450.0,
      rating: 4.9,
      reviewCountText: '1.3k+',
      deliveryTime: '30-40 min',
      deliveryFeeLkr: 200.0,
      imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: true,
      isSpecial: true,
      isHalal: true,
      servesText: '12 Pieces Assorted',
      signatureTag: 'FRESH SASHIMI',
      signatureItemName: 'Salmon & Tuna Sushi',
      signatureItemPriceLkr: 3450.0,
    ),
    FoodItem(
      id: 'jp_ramen',
      name: 'Tokyo Tonkotsu Chicken Ramen',
      sinhalaName: 'ටෝකියෝ චිකන් රාමන්',
      restaurantId: 'rest_samurai',
      restaurantName: 'Samurai Sushi & Ramen Bar',
      restaurantSubtitle: 'Rich Broth Ramen Bowls',
      country: 'Japan',
      category: 'Noodles & Wok',
      menuCategory: 'Ramen Bowls',
      description: 'Rich 12-hour simmered chicken broth with springy wheat ramen noodles, soy-marinated ajitsuke egg, nori seaweed, bamboo shoots, and scallions.',
      priceLkr: 2400.0,
      rating: 4.8,
      reviewCountText: '1.1k+',
      deliveryTime: '30-35 min',
      deliveryFeeLkr: 200.0,
      imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=800&q=80',
      isOpenNow: true,
      isBestseller: false,
      isSpecial: false,
      isHalal: true,
      servesText: 'Large Broth Bowl',
      signatureTag: 'RICH BROTH',
      signatureItemName: 'Tonkotsu Chicken Ramen',
      signatureItemPriceLkr: 2400.0,
    ),
  ];

  static List<FoodItem> getItemsByCategory(String categoryName) {
    if (categoryName == 'All') return mockFoodItems;
    return mockFoodItems.where((item) => item.category == categoryName).toList();
  }

  static List<FoodItem> getItemsByCountry(String countryName) {
    if (countryName == 'All') return mockFoodItems;
    return mockFoodItems.where((item) => item.country.toLowerCase() == countryName.toLowerCase()).toList();
  }

  static List<FoodItem> getItemsByRestaurant(String restaurantId) {
    return mockFoodItems.where((item) => item.restaurantId == restaurantId).toList();
  }

  static List<RestaurantModel> getRestaurantsByCountry(String countryName) {
    if (countryName == 'All') return mockRestaurants;
    return mockRestaurants.where((r) => r.country.toLowerCase() == countryName.toLowerCase()).toList();
  }

  static RestaurantModel? getRestaurantById(String id) {
    try {
      return mockRestaurants.firstWhere((r) => r.id == id);
    } catch (_) {
      return mockRestaurants.isNotEmpty ? mockRestaurants.first : null;
    }
  }

  static List<FoodItem> searchItems(String query) {
    if (query.isEmpty) return mockFoodItems;
    final lower = query.toLowerCase();
    return mockFoodItems.where((item) {
      return item.name.toLowerCase().contains(lower) ||
          item.restaurantName.toLowerCase().contains(lower) ||
          item.description.toLowerCase().contains(lower) ||
          item.category.toLowerCase().contains(lower) ||
          item.country.toLowerCase().contains(lower);
    }).toList();
  }

  static String get host {
    if (!kIsWeb && Platform.isAndroid) {
      return '10.0.2.2';
    }
    return 'localhost';
  }

  static String get apiUrl => 'http://$host/food_api/get_foods.php';

  static Future<List<FoodItem>> fetchFoodItemsFromApi() async {
    try {
      final response = await http.get(Uri.parse(apiUrl));
      if (response.statusCode == 200) {
        List<dynamic> jsonList = jsonDecode(response.body);
        if (jsonList.isNotEmpty) {
          return jsonList.map((item) => FoodItem.fromJson(item)).toList();
        }
      }
    } catch (e) {
      debugPrint('MySQL API connection note: $e (using rich built-in catalog)');
    }
    return mockFoodItems;
  }
}
